version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: task_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: task_db
      MYSQL_USER: root
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: flask_app
    restart: always
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:userpassword@db/task_db
      - FLASK_ENV=development  # Change to 'production' in a production environment
      - JWT_SECRET_KEY=your_secret_key
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
